### ISSUE TITLE
Queries broken after upgrading to 2.4.3

### ISSUE THREAD

**Issue by GaikwadPratik** [rethinkdb/rethinkdb-ts#63]
@ronzeidman, 
I was creating package for our product and didn't realize  a new package for `rethinkdb-ts` was released. So npm updated the package and now I'm getting below errors suddenly

```
lib/handlers/actions/firmware-action.ts:84:18 - error TS2345: Argument of type '(host: RDatum<IHost>) => RDatum<Partial<IHost>>' is not assignable to parameter of type 'IHost | RDatum<IHost> | ((arg: RDatum<IHost>) => any)'.
  Type '(host: RDatum<IHost>) => RDatum<Partial<IHost>>' is missing the following properties from type 'RDatum<IHost>': do, getField, nth, default, and 103 more.

84         .replace((host: RDatum<IHost>) => host.without({ appliance: { firmware: { nextFirmware: true } } }), { returnChanges: true }).getField("changes").nth(0).getField("new_val").run()
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

lib/handlers/actions/guest-action.ts:61:67 - error TS2345: Argument of type '(g: RDatum<IGuest>) => RDatum<any>' is not assignable to parameter of type 'IGuest | RDatum<IGuest> | ((arg: RDatum<IGuest>) => any)'.
  Type '(g: RDatum<IGuest>) => RDatum<any>' is missing the following properties from type 'RDatum<IGuest>': do, getField, nth, default, and 103 more.

61         await r.table<IGuest>(Table.Guest).get(guestName).replace((g: RDatum<IGuest>) => g.without("disks").merge({ disks: _disks })).run();
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

lib/handlers/actions/guest-action.ts:70:79 - error TS2345: Argument of type '(g: RDatum<IPool>) => RDatum<any>' is not assignable to parameter of type 'IPool | RDatum<IPool> | ((arg: RDatum<IPool>) => any)'.
  Type '(g: RDatum<IPool>) => RDatum<any>' is missing the following properties from type 'RDatum<IPool>': do, getField, nth, default, and 103 more.

70           await r.table<IPool>(Table.Pool).get(_dbGuestRecord.poolId).replace((g: RDatum<IPool>) => g.without({ "guestProfile": "disks" }).merge({ guestProfile: { disks: _disks } })).run();
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

lib/handlers/actions/host-action.ts:25:17 - error TS2345: Argument of type '(config: RDatum) => RDatum<any>' is not assignable to parameter of type 'IRethinkServerConfig | { id?: string | undefined; name?: string | undefined; tags?: string[] | undefined; cache_size_mb?: number | "auto" | undefined; } | RDatum<...> | ((arg: RDatum<...>) => any)'.
  Type '(config: RDatum<any>) => RDatum<any>' is missing the following properties from type 'RDatum<DeepPartial<IRethinkServerConfig>>': do, getField, nth, default, and 103 more.

25         .update((config: RDatum) => config.merge({ tags: config("tags").default([]).filter(tag => tag.ne("hio_config")).append("maintenance") }))
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

lib/handlers/actions/host-action.ts:42:17 - error TS2345: Argument of type '(config: RDatum) => RDatum<any>' is not assignable to parameter of type 'IRethinkServerConfig | { id?: string | undefined; name?: string | undefined; tags?: string[] | undefined; cache_size_mb?: number | "auto" | undefined; } | RDatum<...> | ((arg: RDatum<...>) => any)'.
  Type '(config: RDatum<any>) => RDatum<any>' is missing the following properties from type 'RDatum<DeepPartial<IRethinkServerConfig>>': do, getField, nth, default, and 103 more.

42         .update((config: RDatum) => config.merge({ tags: config("tags").default([]).filter(tag => tag.ne("maintenance")) })
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Most of the queries seems to be related to `merge` and `without` returning `RDatum<Partial<T>>`. All of these were fine with package `2.4.2`. I'm not sure why changing target from `es2017` to `ES2017` would suddenly start breaking. Our package is pointing to `ES2019` target but it used to work with `2.4.2` version of `rethinkdb-ts`

P.S. I've reverted back to 2.4.2 for the time being and it just works.

**Comment by atassis** [comment]
@GaikwadPratik can you provide the code example? I'll check this

**Comment by GaikwadPratik** [comment]
@atassis , 

for instance code for 
```
lib/handlers/actions/guest-action.ts:61:67 - error TS2345: Argument of type '(g: RDatum<IGuest>) => RDatum<any>' is not assignable to parameter of type 'IGuest | RDatum<IGuest> | ((arg: RDatum<IGuest>) => any)'.
  Type '(g: RDatum<IGuest>) => RDatum<any>' is missing the following properties from type 'RDatum<IGuest>': do, getField, nth, default, and 103 more.

61         await r.table<IGuest>(Table.Guest).get(guestName).replace((g: RDatum<IGuest>) => g.without("disks").merge({ disks: _disks })).run();
```
IS =>

```
await r.table<IPool>(Table.Pool).get(_dbGuestRecord.poolId).replace((g: RDatum<IPool>) => g.without({ "guestProfile": "disks" }).merge({ guestProfile: { disks: _disks } })).run();
```

**Comment by atassis** [comment]
@GaikwadPratik the github repo or smth? Or can you reduce the typings to simple examples so I can copy paste?

**Comment by atassis** [comment]
```typescript
import { r, RDatum } from 'rethinkdb-ts';

type IPool = Record<string, unknown>;
const disks: any[] = [];

async function bootstrap() {
  await r
    .table<IPool>('table')
    .get('www')
    .replace((g: RDatum<IPool>) =>
      g.without({ guestProfile: 'disks' }).merge({ guestProfile: { disks } }),
    )
    .run();
}

bootstrap();

```
@GaikwadPratik I have made an example by my own (tried to suggest what's happening) and it works fine with [this PR](https://github.com/rethinkdb/rethinkdb-ts/pull/66)

**Comment by atassis** [comment]
Closing an issue since no examples were provided. If you can provide them, reopen the current issue with examples, please
