### ISSUE TITLE
Class 'Cursor' incorrectly implements interface 'RCursor<any>'

### ISSUE THREAD

**Issue by BannerBomb** [rethinkdb/rethinkdb-ts#72]
**Describe the bug**
When attempting to compile a script that imports rethinkdb-ts I end up getting an error which started happening after 2.4.6 update but works fine on 2.4.5. I did some debugging and removed some code to see if it was something in my file and it seems to happen as long as you are importing the module in the file `import { r } from 'rethinkdb-ts';`
```console
bannerbomb@DESKTOP-B66Q6A0:/mnt/c/Users/Admin/Downloads/New folder$ npm run-script tsc

> new-folder@1.0.0 tsc /mnt/c/Users/Admin/Downloads/New folder
> tsc -b

node_modules/rethinkdb-ts/lib/response/cursor.d.ts:7:22 - error TS2420: Class 'Cursor' incorrectly implements interface 'RCursor<any>'.
  Type 'Cursor' is missing the following properties from type 'RCursor<any>': locked, cancel, getReader, pipeThrough, and 2 more.

7 export declare class Cursor extends Readable implements RCursor {
                       ~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-folder@1.0.0 tsc: `tsc -b`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-folder@1.0.0 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bannerbomb/.npm/_logs/2021-01-29T00_12_32_203Z-debug.log
bannerbomb@DESKTOP-B66Q6A0:/mnt/c/Users/Admin/Downloads/New folder$
```

**To Reproduce**
1. Just setup a TS workspace and make a file with an import for rethinkdb-ts then run tsc -b to compile the project.

**Expected behavior**
It was expected to compile and not error.

**Screenshots**

**System info**
 - OS: Ubuntu 18.04.2 LTS
 - RethinkDB Version: 2.4.6 for rethinkdb-ts and 2.4.1~0 for the actual rethinkdb database. You don't need the database when compiling the project since the code isn't doing anything yet.

**Additional context**
If needed my tsconfig.json file contains.

```json
// https://schemastore.azurewebsites.net/schemas/json/tsconfig.json#definitions/compilerOptionsDefinition/properties/compilerOptions
{
	"compilerOptions": {
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"allowJs": false,
		"checkJs": false,
		"declaration": false,
		"target": "ES2020",
		"useDefineForClassFields": true,
		"module": "none",
		"moduleResolution": "node",
		"baseUrl": ".",
		"strict": true,
		"sourceMap": true,
		"importHelpers": false,
		"noEmitHelpers": true,
		"composite": false,
		"noImplicitAny": false,
		"pretty": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true
	},
	"include": [
		"*"
	],
	"exclude": [
		"**/node_modules",
		"src/resources",
		"**/*.spec.ts"
	]
}
```

and the package.json file that I was testing with contains.
```json
{
  "name": "new-folder",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "tsc": "tsc -b"
  },
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^14.14.22",
    "rethinkdb-ts": "^2.4.6",
    "typescript": "^4.1.3"
  }
}
```

**Comment by atassis** [comment]
I'll try to fix this in a few days

**Comment by atassis** [comment]
@BannerBomb finally new version was released. Please, check and comment about results

**Comment by BannerBomb** [comment]
I've updated and it's working now. Thanks,

**Comment by atassis** [comment]
If you are interested- you can join our slack and help me in testing the new version of this library
